# Generated by Django 3.2.14 on 2022-07-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subjext',
            new_name='subject',
        ),
    ]
